services:
  mysql:
    image: mysql:8.0
    container_name: mysql-footfair
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: footfair
      MYSQL_USER: daniel
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
    backend:
        driver: bridge